// Generated by https://quicktype.io

export interface IEfrTiendaCategories {
  error: any,
  data?: IEfrTiendaCategoriesDatum[];
}
//
export interface IEfrTiendaCategoriesDatum {
  id:         number;
  name:        string;
  created_at:   string;
  updated_at:   string;
  products:    IProduct[];
}

export interface IProduct {
  id:         number;
  name:        string;
  description: string;
  price:       number;
  image_url:   string;
  createdAt:   string;
  updatedAt:   string;
  publishedAt: string;
  currency:    string;
  model:       string;
}

// export interface Meta {
//   pagination: Pagination;
// }

// export interface Pagination {
//   page:      number;
//   pageSize:  number;
//   pageCount: number;
//   total:     number;
// }
