// Generated by https://quicktype.io

export interface IPokemonListResponse {
  count:    number;
  next:     string;
  previous: string;
  results:  IPokemonInfo[];
}

export interface IPokemonInfo {
  name: string;
  url:  string;
}
